$schema: https://raw.githubusercontent.com/tabarra/txAdmin-recipes/main/schema.json

name: Trenches RP Base
author: NateTrill
description: QBCore server with Trenches crafting
version: 1.0.0

tasks:
- action: download_github
src: qbcore-framework/qb-core
ref: main
dest: ./resources/[qb]/qb-core

- action: download_github
src: NateTrill/trenches-rp-recipe
ref: main
dest: ./resources

- action: replace_string
file: server.cfg
search: "# QB Resources"
replace: |
# QB Resources
ensure qb-core
ensure trenches_crafting
